//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asiento
    {
        public int id_asiento { get; set; }
        public Nullable<int> id_sala { get; set; }
        public string numero_asiento { get; set; }
    
        public virtual sala sala { get; set; }
    }
}
