//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket_asiento
    {
        public int id_ticket_asiento { get; set; }
        public int id_ticket { get; set; }
        public int id_asiento { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
    
        public virtual asiento asiento { get; set; }
        public virtual ticket ticket { get; set; }
    }
}
